# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MPSCDresdenDialog
                                 A QGIS plugin
 Classification of buildings in Dresden
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-28
        git sha              : $Format:%H$
        copyright            : (C) 2024 by HTW Dresden
        email                : alexander.bong@htw-dresden.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import pandas as pd
import psycopg2
import traceback
import configparser

from qgis.PyQt import uic
from qgis.core import QgsMessageLog, Qgis, QgsProject

from PyQt5 import uic
from PyQt5.QtWidgets import QDialog

from .data_loader import DataLoader
from .geometry_processor import GeometryProcessor
from .citydb_processor import CityDBProcessor
from .citydb_extender import CityDBExtender
from .mapping_processor import MappingProcessor
from .building_values_processor import BuildingValuesProcessor
from .model_trainer import ModelTrainer
from .validate_model import ValidateModel
from .classify_data import ClassifyData
from .manual_correction import ManualCorrection
from .citygml_updater import CityGMLUpdater

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'building_classificator_dialog_base.ui'))


class MPSCDresdenDialog(QDialog, FORM_CLASS):
    """
    Dialog und zentrale Steuereinheit für das QGIS-Plugin zur Gebäudeklassifikation in Dresden.

    Diese Klasse bietet Methoden zum:
    - Laden, Filtern und Exportieren von Gebäudedaten und Flurstücken
    - Geometrische Verarbeitung und Transformation der Daten
    - Aufbau und Erweiterung der CityDB sowie Feature Engineering
    - Mapping, Attributübertragung und Layer-Kategorisierung
    - Training, Validierung und Klassifikation von Modellen
    - Manuelle Korrektur und Retraining
    - Aktualisierung von CityDB-Tabellen und CityGML-Dateien
    - Verwaltung des Plugin-Zustands und der Layer in QGIS
    """    
    
    def __init__(self, iface, parent=None):
        """Constructor."""
        super(MPSCDresdenDialog, self).__init__(parent)
        self.setupUi(self)
        self.pushButton_load_data.clicked.connect(self.loading)
        self.pushButton_filter_merge.clicked.connect(self.filtering)
        self.pushButton_overlapping_geometries.clicked.connect(self.processing_overlapping)
        self.pushButton_transform_validate.clicked.connect(self.transform_and_validate)
        self.pushButton_load_built_up_parcel_layer.clicked.connect(self.load_built_up_parcel_layer)
        self.pushButton_filter_citydb.clicked.connect(self.filter_citydb)
        self.pushButton_extend_citydb.clicked.connect(self.extend_citydb)
        self.pushButton_check_mapping.clicked.connect(self.check_mapping)
        self.pushButton_building_values.clicked.connect(self.calculate_building_values)
        self.pushButton_training.clicked.connect(self.train_model)
        self.pushButton_validation.clicked.connect(self.validate_model)
        self.pushButton_classification.clicked.connect(self.classify_data)
        self.pushButton_select.clicked.connect(self.select)
        self.pushButton_correct.clicked.connect(self.correct)
        self.pushButton_retrain.clicked.connect(self.retrain)
        self.pushButton_revalidate.clicked.connect(self.revalidate)
        self.pushButton_reclassify.clicked.connect(self.reclassify)
        self.pushButton_updatecitydb_filter.clicked.connect(self.update_citydb_filter)
        self.pushButton_updatecitygml.clicked.connect(self.update_citygml_files)

        # Initialize attributes to store loaded data
        self.building_development_df = pd.DataFrame()
        self.parcels_df = pd.DataFrame()
        
        # Initialize attributes to store filtered data
        self.filtered_building_development_df = pd.DataFrame()
        self.filtered_parcels_df = pd.DataFrame()
        
        # Initialize attributes to store vector layers
        self.building_development_layer = None
        self.parcels_layer = None
        self.citydb_filter_layer = None
        
        # Load CityDB connection parameters from config file
        config = configparser.ConfigParser()
        config.read(os.path.join(os.path.dirname(__file__), 'config.ini'))
        self.connection_params = {
            'host': config.get('Database', 'host'),
            'port': config.get('Database', 'port'),
            'dbname': config.get('Database', 'dbname'),
            'user': config.get('Database', 'user'),
            'password': config.get('Database', 'password')
        }
        
        self.conn = psycopg2.connect(
            host=self.connection_params['host'],
            port=self.connection_params['port'],
            dbname=self.connection_params['dbname'],
            user=self.connection_params['user'],
            password=self.connection_params['password']
        )
        self.cur = self.conn.cursor()
        self.iface = iface
        
        self.data_loader = DataLoader(self.conn, self.cur, self.connection_params)
        self.geometry_processor = GeometryProcessor(self.conn, self.cur, self.connection_params)
        self.citydb_processor = CityDBProcessor(self.conn, self.cur, self.connection_params)
        self.citydb_extender = CityDBExtender(self.conn, self.cur, self.connection_params)
        self.mapping_processor = MappingProcessor(self.conn, self.cur, self.connection_params)
        self.value_processor = BuildingValuesProcessor()
        self.model_trainer = ModelTrainer(self.conn, self.cur, self.connection_params)
        self.model_validator = ValidateModel(self.conn, self.cur, self.connection_params)
        self.model_classifier = ClassifyData(self.conn, self.cur, self.connection_params)
        self.manual_correction = ManualCorrection(self.iface, self.conn, self.cur, self.connection_params)
        self.citygml_updater = CityGMLUpdater(self.conn, self.cur, self.connection_params)

    def loading(self):
        load_building_development = self.checkBox_Bebauung.isChecked()
        load_parcels = self.checkBox_Flurstuecke.isChecked()

        if load_building_development:
            self.building_development_df = self.data_loader.load_csv(self.data_loader.paths['building_development'])
            QgsMessageLog.logMessage("building_development data loaded.", level=Qgis.Info)

        if load_parcels:
            self.parcels_df = self.data_loader.load_csv(self.data_loader.paths['parcels'])
            QgsMessageLog.logMessage("parcels data loaded.", level=Qgis.Info)
            
        return self.building_development_df, self.parcels_df
        
    def filtering(self):

        if not self.building_development_df.empty:
            self.filtered_building_development_df = self.data_loader.filter_data('building_development', self.building_development_df)
            QgsMessageLog.logMessage("Filtered building_development data.", level=Qgis.Info)
            
        if not self.parcels_df.empty:
            self.filtered_parcels_df = self.data_loader.filter_data('parcels', self.parcels_df)
            QgsMessageLog.logMessage("Filtered parcels data.", level=Qgis.Info)

        # Vektorlayer erstellen
        self.building_development_layer = self.data_loader.create_vector_layer(self.filtered_building_development_df, 'building_development', 'geometry_building_development', 'srid_building_development')
        self.parcels_layer = self.data_loader.create_vector_layer(self.filtered_parcels_df, 'parcels', 'geometry_parcels', 'srid_parcels')

        self.save_layer_as_qlr(self.building_development_layer, 'building_development_layer')
        self.save_layer_as_qlr(self.parcels_layer, 'parcels_layer')
        
        self.data_loader.export_layer_to_citydb(self.building_development_layer, 'building_development')
        self.data_loader.export_layer_to_citydb(self.parcels_layer, 'parcels')
        
        return self.filtered_building_development_df, self.filtered_parcels_df 
        
    def processing_overlapping(self):
        try:
            self.geometry_processor.create_schema_if_not_exists()
            self.geometry_processor.create_built_up_parcel_table()
            self.geometry_processor.create_indexes()
            self.geometry_processor.process_overlapping_geometries()
                       
        except Exception as e:
            QgsMessageLog.logMessage(f"Error during geometric processing: {str(e)}", level=Qgis.Critical)
            
    def transform_and_validate(self):
        try:
            target_epsg = int(self.lineEdit_EPSG_Code.text())
            self.geometry_processor.transform_built_up_parcel_table(target_epsg)
            QgsMessageLog.logMessage(f"Transformation to EPSG:{target_epsg} completed.", level=Qgis.Info)
        except ValueError:
            QgsMessageLog.logMessage("Invalid EPSG code entered.", level=Qgis.Warning)
        except Exception as e:
            QgsMessageLog.logMessage(f"Error during transformation: {str(e)}", level=Qgis.Critical)
            
    def load_built_up_parcel_layer(self):
        try:
            built_up_parcel_layer = self.data_loader.load_layer_from_db(self.connection_params, 'MPSCDresden', 'built_up_parcel')
            if built_up_parcel_layer:
                QgsMessageLog.logMessage("built_up_parcel layer loaded into QGIS.", level=Qgis.Info)
            else:
                QgsMessageLog.logMessage("Failed to load built_up_parcel layer into QGIS.", level=Qgis.Critical)
        except Exception as e:
            QgsMessageLog.logMessage(f"Error loading built_up_parcel layer: {str(e)}", level=Qgis.Critical)
            
    def check_mapping(self):
        try:
            kartierung_dd_gesamt_layer = QgsProject.instance().mapLayersByName('Kartierung_DD_Gesamt')[0]
            
            # Exportiere den Layer in die Datenbank
            self.data_loader.export_layer_to_citydb(kartierung_dd_gesamt_layer, 'kartierung_dd_gesamt', drop_existing=True)
            self.mapping_processor.add_additional_columns()
            
            # Transferiere Attribute und kategorisiere Layer
            self.mapping_processor.transfer_attributes_to_kartierung_dd_gesamt()
            self.mapping_processor.compare_and_categorize_layers()
            
            # Lade den Layer neu in QGIS
            layer = self.data_loader.load_layer_from_db(self.connection_params, 'MPSCDresden', 'kartierung_dd_gesamt')
            if layer:
                self.mapping_processor.categorize_and_colorize(layer)
                QgsProject.instance().addMapLayer(layer)
                QgsMessageLog.logMessage("Kartierung_DD_Gesamt layer reloaded into QGIS.", level=Qgis.Info)
            else:
                QgsMessageLog.logMessage("Failed to reload Kartierung_DD_Gesamt layer into QGIS.", level=Qgis.Critical)
        except Exception as e:
            QgsMessageLog.logMessage(f"Error in check_mapping: {str(e)}", level=Qgis.Critical)
            
    def filter_citydb(self):
        try:
            self.citydb_processor.create_tables()
            self.citydb_processor.fill_table()
            self.citydb_processor.update_function_from_csv()
            self.citydb_processor.filter_table()
            self.citydb_processor.fill_remaining_attributes_and_geometry()
            self.citydb_processor.calculate_footprint()
            self.citydb_processor.calculate_eaves_height()
            self.citydb_processor.calculate_storey_height()
            self.citydb_processor.count_roof_surfaces()
            self.citydb_processor.calculate_roof_slope()
            self.citydb_processor.intersect_and_update_citydb_filter()
            self.citydb_processor.clean_sst_data()
            self.citydb_processor.calculate_clusters()
            self.citydb_processor.set_default_values()
            self.citydb_processor.calculate_neighbors()
            self.citydb_processor.add_feature_engineering_attributes()
            self.citydb_processor.calculate_geometric_features()
            QgsMessageLog.logMessage("CityDB table filled successfully", level=Qgis.Info)
        except Exception as e:
            QgsMessageLog.logMessage(f"Error filtering CityDB: {str(e)}", level=Qgis.Critical)
            
    def extend_citydb(self):
        try:
            neubauten = QgsProject.instance().mapLayersByName('Neubauten seit 1990')[0]
            baualter = QgsProject.instance().mapLayersByName('Adrpkt_DD_2024_Baujahr_ohneVonovia')[0]
            
            self.data_loader.set_crs_for_layer(neubauten, 25833)
            self.data_loader.set_crs_for_layer(baualter, 25833)
            
            self.data_loader.export_layer_to_citydb(neubauten, 'neubauten', drop_existing=True)
            self.data_loader.export_layer_to_citydb(baualter, 'baualter', drop_existing=True)
            
            self.citydb_extender.add_additional_columns()
            self.citydb_extender.reset_columns()
            self.citydb_extender.add_new_buildings()
            self.citydb_extender.update_building_age()
            self.citydb_extender.update_building_age_from_monuments()
            self.citydb_extender.update_sst_from_csv()
            self.citydb_extender.set_classification_source_kartierung()
            
            self.citydb_filter_layer = DataLoader.load_layer_from_db(self.connection_params, 'MPSCDresden', 'citydb_filter')
        except Exception as e:
            QgsMessageLog.logMessage(f"Error extending CityDB: {str(e)}", level=Qgis.Critical)
    
    def calculate_building_values(self):
        self.value_processor.process_values()
        
    def train_model(self):
        try:
            self.model_trainer.split_and_save_data()
            self.model_trainer.train()
            self.model_trainer.save_label_encoders()
            self.model_trainer.load_and_visualize_training_data()
            
            QgsMessageLog.logMessage("Model training completed successfully", level=Qgis.Info)
        except Exception as e:
            QgsMessageLog.logMessage(f"Error during model training: {str(e)}", level=Qgis.Critical)
            QgsMessageLog.logMessage(traceback.format_exc(), level=Qgis.Critical)
        
    def validate_model(self):
        try:
            self.model_validator.validate()
            self.model_validator.load_and_visualize_validation_data()
            
            QgsMessageLog.logMessage("Model validation completed successfully", level=Qgis.Info)
        except Exception as e:
            QgsMessageLog.logMessage(f"Error during model validation: {str(e)}", level=Qgis.Critical)
            QgsMessageLog.logMessage(traceback.format_exc(), level=Qgis.Critical)
            
    def classify_data(self):
        try:
            self.model_classifier.create_result_relation()
            self.model_classifier.classify()
            self.model_classifier.load_and_visualize_classification_data()
            
            QgsMessageLog.logMessage("Data classification completed successfully", level=Qgis.Info)
        except Exception as e:
            QgsMessageLog.logMessage(f"Error during data classification: {str(e)}", level=Qgis.Critical)
            QgsMessageLog.logMessage(traceback.format_exc(), level=Qgis.Critical)
            
    def select(self):
        try:
            self.manual_correction.select_building()
        except Exception as e:
            QgsMessageLog.logMessage(f"Error during selection: {str(e)}", level=Qgis.Critical)
            QgsMessageLog.logMessage(traceback.format_exc(), level=Qgis.Critical)

    def correct(self):
        try:
            new_sst = self.lineEdit.text()
            self.manual_correction.correct_building(new_sst)
            QgsMessageLog.logMessage("Building corrected successfully", level=Qgis.Info)
        except Exception as e:
            QgsMessageLog.logMessage(f"Error during correction: {str(e)}", level=Qgis.Critical)
            QgsMessageLog.logMessage(traceback.format_exc(), level=Qgis.Critical)
            
    def retrain(self):
        try:
            self.manual_correction.retrain_all_levels()
            QgsMessageLog.logMessage("Retraining completed successfully", level=Qgis.Info)
        except Exception as e:
            QgsMessageLog.logMessage(f"Error during retraining: {str(e)}", level=Qgis.Critical)
            QgsMessageLog.logMessage(traceback.format_exc(), level=Qgis.Critical)
            
    def revalidate(self):
        try:
            self.validate_model()
            QgsMessageLog.logMessage("Revalidation completed successfully", level=Qgis.Info)
        except Exception as e:
            QgsMessageLog.logMessage(f"Error during revalidation: {str(e)}", level=Qgis.Critical)
            QgsMessageLog.logMessage(traceback.format_exc(), level=Qgis.Critical)
            
    def reclassify(self):
        try:
            self.classify_data()
            QgsMessageLog.logMessage("Reclassification completed successfully", level=Qgis.Info)
        except Exception as e:
            QgsMessageLog.logMessage(f"Error during reclassification: {str(e)}", level=Qgis.Critical)
            QgsMessageLog.logMessage(traceback.format_exc(), level=Qgis.Critical)
            
    def update_citydb_filter(self):
        try:
            self.citygml_updater.update_citydb_filter()
            self.citygml_updater.load_and_visualize_citydb_filter()
            QgsMessageLog.logMessage("CityDB_Filter updated successfully", level=Qgis.Info)
        except Exception as e:
            QgsMessageLog.logMessage(f"Error updating CityGML files: {str(e)}", level=Qgis.Critical)
            QgsMessageLog.logMessage(traceback.format_exc(), level=Qgis.Critical)
    
    def update_citygml_files(self):
        try:
            self.citygml_updater.update_citygml_files(test_mode=False)
            QgsMessageLog.logMessage("CityGML files updated successfully", level=Qgis.Info)
        except Exception as e:
            QgsMessageLog.logMessage(f"Error updating CityGML files: {str(e)}", level=Qgis.Critical)
            QgsMessageLog.logMessage(traceback.format_exc(), level=Qgis.Critical)
            
    def close_db_connection(self):
        if self.cur:
            self.cur.close()
        if self.conn:
            self.conn.close()
        QgsMessageLog.logMessage("Closed connection to CityDB", level=Qgis.Info)