[Paths]
#in data_loader
building_development = import_data/Bebauung.csv
parcels = import_data/Flurstücke.csv

#in building_values_processor
building_values_file = export_data/building_values.txt
values_separate_file = export_data/building_values_separate.txt
building_values_csv_file = export_data/building_values.csv
values_separate_csv_file = export_data/building_values_separate.csv

#in citydb_processor
building_function_csv = import_data/Gebaeude_f_Bestand_kurz.csv
#in citydb_extender
additional_sst = import_data/Nachkartierung_Gesamt_2025_05.csv
building_age_monuments = import_data/Baualter_Denkmäler.csv

#in model_trainer
model_dir = Modelltraining
#in validate_model
vis_path = Validierung
#in classify_data
confidence_report = export_data/confidence_report.txt

#in citygml_updater
input_citygml_dir = D:\01_Forschung_Lehre\03_Digitaler_Starkregenzwilling\01_Bestehende_Daten\CityGML\LOD2_citygml_v202407\citygml
output_citygml_dir = D:\01_Forschung_Lehre\03_Digitaler_Starkregenzwilling\07_Ergebnisdaten\citygml

[Database]
host = localhost
port = 5432
dbname = CityDBDD_V5
user = postgres
password = MPSCDresden